#!/bin/sh

DAEMON=/usr/bin/schilling-node-app-wrapper
PIDFILE=/var/run/schilling-node-app.pid

case "$1" in
    start)
        printf "Starting schilling-node-app... "
        start-stop-daemon -S -b -m -p "$PIDFILE" -x /bin/sh -- -c "$DAEMON > /dev/console 2>&1" && echo "" || echo "FAILED"
        ;;
    stop)
        printf "Stopping schilling-node-app... "
        start-stop-daemon -K -p "$PIDFILE" && echo "done" || echo "FAILED"
        rm -f "$PIDFILE"
        ;;
    restart)
        "$0" stop
        "$0" start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
