#!/bin/sh

DAEMON=/usr/bin/schilling-node-app-wrapper
PIDFILE=/var/run/schilling-node-app.pid

case "$1" in
    start)
        printf "Starting schilling-node-app... "
        if start-stop-daemon -S -b -m -p "$PIDFILE" -x "$DAEMON"; then
            echo "OK"
        else
            echo "FAILED"
            exit 1
        fi
        ;;
    stop)
        printf "Stopping schilling-node-app... "
        if start-stop-daemon -K -p "$PIDFILE" -x "$DAEMON"; then
            echo "done"
            rm -f "$PIDFILE"
        else
            echo "FAILED"
            exit 1
        fi
        ;;
    restart)
        "$0" stop
        "$0" start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
